dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - lcov
    - libboost-test-dev
    - libspdlog-dev
    - libgtest-dev
script:
- export
- env
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
# - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#   - curl -f -T cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ushebdim:$API_BINTRAY_KEY "https://api.bintray.com/content/ilia64/otus_cpp/homework/$TRAVIS_BUILD_NUMBER/;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  provider: bintray
  file: bintray.json
  user: shebdim
  key: $BINTRAY_API_KEY
  skip_cleanup: false
