os:
  - linux
  - osx
  - windows
dist: bionic
language: cpp
compiler: clang
addons:
  sonarcloud:
    organization: shebdim
    token:
      secure: $SONAR_TOKEN
  apt:
    packages:
    - lcov
    - libboost-test-dev
    - libspdlog-dev
    - libgtest-dev
before_install:
  - pip install --user cpp-coveralls
script:
- export
- env
- cmake .
- build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory cmake --build .
- sonar-scanner
- cmake --build . --target test
- cmake --build . --target package
# - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'
deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#   - curl -f -T cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ushebdim:$API_BINTRAY_KEY "https://api.bintray.com/content/ilia64/otus_cpp/homework/$TRAVIS_BUILD_NUMBER/;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  provider: bintray
  file: bintray.json
  user: shebdim
  key: $BINTRAY_API_KEY
  skip_cleanup: true
