dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - lcov
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
